volumes:
  postgres:
  redis:


services:
  app:
    build:
      context: ./backend
    environment:
      POSTGRESQL_USER: $POSTGRESQL_USER
      POSTGRESQL_HOST: $POSTGRESQL_HOST
      POSTGRESQL_PASSWORD: $POSTGRESQL_PASSWORD
      POSTGRESQL_DATABASE: $POSTGRESQL_DATABASE
      POSTGRESQL_PORT: $POSTGRESQL_PORT

      REDIS_HOST: $REDIS_HOST

      IS_DEBUG: False
      PYTHONUNBUFFERED: 1
      SQLALCHEMY_WARN_20: 1
    deploy:
      replicas: $APP_REPLICAS
    depends_on:
      - postgres
      - redis

  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - 80:80
    volumes:
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - app

  postgres:
    build:
      context: ./docker_files
      dockerfile: postgres.dockerfile
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_DB: $POSTGRESQL_DATABASE
      POSTGRES_PASSWORD: $POSTGRESQL_PASSWORD
      PGDATA: /var/lib/postgresql/data  # to not lose data on image updates https://stackoverflow.com/a/62301253
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0.5-alpine
    command: --loglevel warning
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - redis:/data
