import os


class Tokens:
    POSTGRESQL_USER = os.getenv('POSTGRESQL_USER')
    POSTGRESQL_PASSWORD = os.getenv('POSTGRESQL_PASSWORD')
    POSTGRESQL_HOST = os.getenv('POSTGRESQL_HOST')
    POSTGRESQL_DATABASE = os.getenv('POSTGRESQL_DATABASE')

    REDIS_HOST = os.getenv('REDIS_HOST')

    ALEMBIC_POSTGRESQL_HOST = os.getenv('ALEMBIC_POSTGRESQL_HOST')

    POSTGRESQL_URL = f'postgresql+asyncpg://{POSTGRESQL_USER}:{POSTGRESQL_PASSWORD}' \
                     f'@{POSTGRESQL_HOST}/{POSTGRESQL_DATABASE}'
    ALEMBIC_POSTGRESQL_URL = f'postgresql://{POSTGRESQL_USER}:{POSTGRESQL_PASSWORD}' \
                             f'@{ALEMBIC_POSTGRESQL_HOST}/{POSTGRESQL_DATABASE}'
