"""Add sources

Revision ID: 51b8eda9d059
Revises: 823020bd8211
Create Date: 2022-05-04 17:22:21.127502

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '51b8eda9d059'
down_revision = '823020bd8211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sources',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('url', sa.Text(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    op.create_index(op.f('ix_sources_name'), 'sources', ['name'], unique=False)

    op.create_table(
        'attachments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('disk_filename', sa.String(), nullable=False),
        sa.Column('source_filename', sa.String(), nullable=False),
        sa.Column('size', sa.Integer(), nullable=False),
        sa.Column('source_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_attachments_source_id_sources'), onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    op.create_index(op.f('ix_attachments_source_id'), 'attachments', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_source_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_sources_name'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
