"""Add entities

Revision ID: 12f3c09d78fc
Revises:
Create Date: 2022-04-27 23:31:15.523684

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = '12f3c09d78fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'entities',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('type', sa.Enum('course', 'theme', 'knowledge', 'quantum', 'target', 'metric', 'task', 'activity', 'skill', 'competence', 'profession', 'suos_competence', name='entity_type'), nullable=False),
        sa.Column('size', sa.Enum('small', 'medium', 'large', name='entity_size'), server_default='medium', nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('study_time', sa.Integer(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_entities')),
        sa.UniqueConstraint('name', 'type', name=op.f('uq_entities_name'))
    )
    op.create_index('type__name', 'entities', ['type', 'name'], unique=False)
    op.create_table(
        'entities_types_connections',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('parent_type', sa.Enum(name='entity_type', create_type=False), nullable=False),
        sa.Column('child_type', sa.Enum(name='entity_type', create_type=False), nullable=False),
        sa.Column('parent_column_name', sa.String(), nullable=True),
        sa.Column('child_column_name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_entities_types_connections')),
        sa.UniqueConstraint('parent_type', 'child_type', name=op.f('uq_entities_types_connections_parent_type'))
    )
    op.create_table(
        'entities_connections',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=False),
        sa.Column('child_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['child_id'], ['entities.id'], name=op.f('fk_entities_connections_child_id_entities'), onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['parent_id'], ['entities.id'], name=op.f('fk_entities_connections_parent_id_entities'), onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_entities_connections')),
        sa.UniqueConstraint('parent_id', 'child_id', name=op.f('uq_entities_connections_parent_id'))
    )
    op.create_index(op.f('ix_entities_connections_child_id'), 'entities_connections', ['child_id'], unique=False)
    op.create_index(op.f('ix_entities_connections_parent_id'), 'entities_connections', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entities_connections_parent_id'), table_name='entities_connections')
    op.drop_index(op.f('ix_entities_connections_child_id'), table_name='entities_connections')
    op.drop_table('entities_connections')
    op.drop_table('entities_types_connections')
    op.drop_index('type__name', table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
    ENUM(name='entity_type').drop(op.get_bind(), checkfirst=False)
    ENUM(name='entity_size').drop(op.get_bind(), checkfirst=False)
