"""Add users

Revision ID: 59418646e0cd
Revises: a5a2dbb6625c
Create Date: 2022-05-04 16:59:25.115246

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = '59418646e0cd'
down_revision = 'a5a2dbb6625c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('password', sa.String(), nullable=False),
        sa.Column('status', sa.Enum('user', 'editor', 'admin', name='user_status'), server_default='user', nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    # ### end Alembic commands ###
    op.create_index(op.f('ix_users_email'), 'users', [sa.text('LOWER(email)')], unique=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
    ENUM(name='user_status').drop(op.get_bind(), checkfirst=False)
