"""Add change log

Revision ID: 95925bf13380
Revises: 871be10a8952
Create Date: 2022-04-27 23:38:40.826798

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = '95925bf13380'
down_revision = '871be10a8952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'change_log',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('type', sa.Enum('create', 'update', 'delete', name='change_type'), nullable=False),
        sa.Column('entity_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_change_log_entity_id_entities'), onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_change_log_user_id_users'), onupdate='CASCADE', ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_change_log'))
    )
    op.create_index(op.f('ix_change_log_entity_id'), 'change_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_change_log_user_id'), 'change_log', ['user_id'], unique=False)
    op.create_table(
        'entities_updates',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('entity_id', sa.Integer(), nullable=False),
        sa.Column('column', sa.Enum('name', 'type', 'size', 'description', 'study_time', name='entity_column'), nullable=False),
        sa.Column('old_value', sa.Text(), nullable=False),
        sa.Column('new_value', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_entities_updates_entity_id_entities'), onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_entities_updates'))
    )
    op.create_index(op.f('ix_entities_updates_entity_id'), 'entities_updates', ['entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entities_updates_entity_id'), table_name='entities_updates')
    op.drop_table('entities_updates')
    op.drop_index(op.f('ix_change_log_user_id'), table_name='change_log')
    op.drop_index(op.f('ix_change_log_entity_id'), table_name='change_log')
    op.drop_table('change_log')
    # ### end Alembic commands ###
    ENUM(name='change_type').drop(op.get_bind(), checkfirst=False)
    ENUM(name='entity_column').drop(op.get_bind(), checkfirst=False)
