"""Add change log

Revision ID: 823020bd8211
Revises: 59418646e0cd
Create Date: 2022-05-04 17:19:43.920842

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = '823020bd8211'
down_revision = '59418646e0cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'change_log',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('editor_id', sa.Integer()),
        sa.Column('type', sa.Enum('create', 'update', 'delete', name='change_type'), nullable=False),
        sa.Column('table', sa.Enum('entities', 'entities_connections', 'entities_types_connections', 'hidden_courses', 'users', name='changed_table'), nullable=False),
        sa.Column('element_id', sa.Integer(), nullable=False),
        sa.Column('parent_change_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['editor_id'], ['users.id'], name=op.f('fk_change_log_editor_id_users'), onupdate='CASCADE', ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['parent_change_id'], ['change_log.id'], name=op.f('fk_change_log_parent_change_id_change_log'), onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_change_log'))
    )
    op.create_index(op.f('ix_change_log_parent_change_id'), 'change_log', ['parent_change_id'], unique=False)
    op.create_index(op.f('ix_change_log_element_id'), 'change_log', ['element_id'], unique=False)

    op.create_table(
        'archived_db_elements',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('element_data', sa.JSON(), nullable=False),
        sa.Column('change_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['change_id'], ['change_log.id'], name=op.f('fk_archived_db_elements_change_id_change_log'), onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_archived_db_elements'))
    )
    op.create_index(op.f('ix_archived_db_elements_change_id'), 'archived_db_elements', ['change_id'], unique=False)

    op.create_table(
        'db_elements_updates',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('column', sa.String(), nullable=False),
        sa.Column('old_value', sa.Text(), nullable=False),
        sa.Column('new_value', sa.Text(), nullable=False),
        sa.Column('change_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['change_id'], ['change_log.id'], name=op.f('fk_db_elements_updates_change_id_change_log'), onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_db_elements_updates'))
    )
    op.create_index(op.f('ix_db_elements_updates_change_id'), 'db_elements_updates', ['change_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_db_elements_updates_change_id'), table_name='db_elements_updates')
    op.drop_table('db_elements_updates')
    op.drop_index(op.f('ix_archived_db_elements_change_id'), table_name='archived_db_elements')
    op.drop_table('archived_db_elements')
    op.drop_index(op.f('ix_change_log_element_id'), table_name='change_log')
    op.drop_index(op.f('ix_change_log_parent_change_id'), table_name='change_log')
    op.drop_table('change_log')
    # ### end Alembic commands ###
    ENUM(name='change_type').drop(op.get_bind(), checkfirst=False)
    ENUM(name='changed_table').drop(op.get_bind(), checkfirst=False)
