"""Add sources

Revision ID: d29a5f44c388
Revises: 9e2601e2c97f
Create Date: 2022-04-27 23:41:05.191543

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = 'd29a5f44c388'
down_revision = '9e2601e2c97f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sources',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('url', sa.Text(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    op.create_index(op.f('ix_sources_name'), 'sources', ['name'], unique=False)
    op.create_table(
        'attachments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('disk_filename', sa.String(), nullable=False),
        sa.Column('source_filename', sa.String(), nullable=False),
        sa.Column('size', sa.Integer(), nullable=False),
        sa.Column('source_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_attachments_source_id_sources'), onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    op.create_index(op.f('ix_attachments_source_id'), 'attachments', ['source_id'], unique=False)
    op.create_table(
        'thumbnails',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('disk_filename', sa.String(), nullable=False),
        sa.Column('size', sa.Enum('small', 'medium', 'large', name='thumbnail_size'), nullable=False),
        sa.Column('height', sa.Integer(), nullable=False),
        sa.Column('width', sa.Integer(), nullable=False),
        sa.Column('attachment_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], name=op.f('fk_thumbnails_attachment_id_attachments'), onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_thumbnails')),
        sa.UniqueConstraint('attachment_id', 'size', name=op.f('uq_thumbnails_attachment_id'))
    )
    op.create_index(op.f('ix_thumbnails_attachment_id'), 'thumbnails', ['attachment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thumbnails_attachment_id'), table_name='thumbnails')
    op.drop_table('thumbnails')
    op.drop_index(op.f('ix_attachments_source_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_sources_name'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
    ENUM(name='thumbnail_size').drop(op.get_bind(), checkfirst=False)
