"""Add entities

Revision ID: a5a2dbb6625c
Revises:
Create Date: 2022-05-04 16:54:21.532823

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import text
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = 'a5a2dbb6625c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    connection = op.get_bind()
    connection.execute(text('CREATE EXTENSION IF NOT EXISTS pg_trgm'))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'entities',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('type', sa.Enum('educational program', 'course', 'theme', 'knowledge', 'quantum', 'target', 'metric', 'task', 'activity', 'skill', 'competence', 'profession', 'suos_competence', 'competence_model', name='entity_type'), nullable=False),
        sa.Column('size', sa.Enum('small', 'medium', 'large', name='entity_size'), server_default='medium', nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('study_time', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_entities'))
    )
    op.create_index(op.f('ix_entities_type'), 'entities', ['type'], unique=False)
    op.create_index('ix_entities_name', 'entities', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')

    op.create_table(
        'entity_type_connections',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('parent_type', sa.Enum(name='entity_type'), nullable=False),
        sa.Column('child_type', sa.Enum(name='entity_type'), nullable=False),
        sa.Column('parent_column_name', sa.String(), nullable=True),
        sa.Column('child_column_name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_type_connections')),
        sa.UniqueConstraint('parent_type', 'child_type', name=op.f('uq_entity_type_connections_parent_type'))
    )

    op.create_table(
        'entity_connections',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=False),
        sa.Column('child_id', sa.Integer(), nullable=False),
        sa.Column('type_connection_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['child_id'], ['entities.id'], name=op.f('fk_entity_connections_child_id_entities'), onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['parent_id'], ['entities.id'], name=op.f('fk_entity_connections_parent_id_entities'), onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['type_connection_id'], ['entity_type_connections.id'], name=op.f('fk_entity_connections_type_connection_id_entity_type_connections'), onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_connections')),
        sa.UniqueConstraint('parent_id', 'child_id', name=op.f('uq_entity_connections_parent_id'))
    )
    op.create_index(op.f('ix_entity_connections_child_id'), 'entity_connections', ['child_id'], unique=False)
    op.create_index(op.f('ix_entity_connections_type_connection_id'), 'entity_connections', ['type_connection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_connections_type_connection_id'), table_name='entity_connections')
    op.drop_index(op.f('ix_entity_connections_child_id'), table_name='entity_connections')
    op.drop_index(op.f('ix_entities_type'), table_name='entities')
    op.drop_table('entity_connections')
    op.drop_table('entity_type_connections')
    op.drop_table('entities')
    # ### end Alembic commands ###
    ENUM(name='entity_type').drop(op.get_bind(), checkfirst=False)
    ENUM(name='entity_size').drop(op.get_bind(), checkfirst=False)
