"""Add hidden courses

Revision ID: 9e2601e2c97f
Revises: 95925bf13380
Create Date: 2022-04-27 23:40:15.605627

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '9e2601e2c97f'
down_revision = '95925bf13380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'hidden_courses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('course_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['course_id'], ['entities.id'], name=op.f('fk_hidden_courses_course_id_entities'), onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_hidden_courses')),
        sa.UniqueConstraint('course_id', name=op.f('uq_hidden_courses_course_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hidden_courses')
    # ### end Alembic commands ###
