"""Add entities

Revision ID: a5a2dbb6625c
Revises:
Create Date: 2022-05-04 16:54:21.532823

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = 'a5a2dbb6625c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'entities',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('type', sa.Enum('course', 'theme', 'knowledge', 'quantum', 'target', 'metric', 'task', 'activity', 'skill', 'competence', 'profession', 'suos_competence', name='entity_type'), nullable=False),
        sa.Column('size', sa.Enum('small', 'medium', 'large', name='entity_size'), server_default='medium', nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('study_time', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_entities')),
        sa.UniqueConstraint('name', 'type', name=op.f('uq_entities_name'))
    )

    op.create_table(
        'entities_types_connections',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('parent_type', sa.Enum('course', 'theme', 'knowledge', 'quantum', 'target', 'metric', 'task', 'activity', 'skill', 'competence', 'profession', 'suos_competence', name='entity_type'), nullable=False),
        sa.Column('child_type', sa.Enum('course', 'theme', 'knowledge', 'quantum', 'target', 'metric', 'task', 'activity', 'skill', 'competence', 'profession', 'suos_competence', name='entity_type'), nullable=False),
        sa.Column('parent_column_name', sa.String(), nullable=True),
        sa.Column('child_column_name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_entities_types_connections')),
        sa.UniqueConstraint('parent_type', 'child_type', name=op.f('uq_entities_types_connections_parent_type'))
    )

    op.create_table(
        'entities_connections',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=False),
        sa.Column('child_id', sa.Integer(), nullable=False),
        sa.Column('types_connection_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['child_id'], ['entities.id'], name=op.f('fk_entities_connections_child_id_entities'), onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['parent_id'], ['entities.id'], name=op.f('fk_entities_connections_parent_id_entities'), onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['types_connection_id'], ['entities_types_connections.id'], name=op.f('fk_entities_connections_types_connection_id_entities_types_connections'), onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_entities_connections')),
        sa.UniqueConstraint('parent_id', 'child_id', name=op.f('uq_entities_connections_parent_id'))
    )
    op.create_index(op.f('ix_entities_connections_child_id'), 'entities_connections', ['child_id'], unique=False)
    op.create_index(op.f('ix_entities_connections_types_connection_id'), 'entities_connections', ['types_connection_id'], unique=False)

    op.create_table(
        'hidden_courses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('course_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['course_id'], ['entities.id'], name=op.f('fk_hidden_courses_course_id_entities'), onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_hidden_courses')),
        sa.UniqueConstraint('course_id', name=op.f('uq_hidden_courses_course_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hidden_courses')
    op.drop_index(op.f('ix_entities_connections_types_connection_id'), table_name='entities_connections')
    op.drop_index(op.f('ix_entities_connections_child_id'), table_name='entities_connections')
    op.drop_table('entities_connections')
    op.drop_table('entities_types_connections')
    op.drop_table('entities')
    # ### end Alembic commands ###
    ENUM(name='entity_type').drop(op.get_bind(), checkfirst=False)
    ENUM(name='entity_size').drop(op.get_bind(), checkfirst=False)
